import json
import tempfile
import unittest
from pathlib import Path

from dip_framework.contracts import ROOT, validate_default_examples, validate_file
from dip_framework.trust_loop import build_trust_loop, write_trust_loop
from dip_framework.v02 import (
    build_product_review_surface,
    build_runtime_readiness_assessment,
    compute_policy_preflight,
    compute_policy_engine,
    compute_simulation,
    evaluate_evidence_store_adapter_parity,
    evaluate_approval_authority,
    evaluate_capability_governance,
    evaluate_durable_case_store_adapter,
    evaluate_durable_evidence_backend,
    evaluate_durable_evidence_store,
    evaluate_external_approval_adapter,
    evaluate_external_approval_boundary,
    evaluate_external_approval_system,
    evaluate_external_identity,
    evaluate_external_identity_integration,
    evaluate_controlled_runtime_execution_gate,
    evaluate_controlled_runtime_pilot_admission,
    evaluate_completion_plan_execution,
    evaluate_governance_closure,
    evaluate_governed_advisory_runtime,
    evaluate_limited_runtime_authority_gate,
    evaluate_live_decision_approval_provider,
    evaluate_live_identity_authority,
    evaluate_live_approval_provider_gate,
    evaluate_live_identity_evidence_gate,
    evaluate_live_identity_rbac,
    evaluate_marketplace_runtime_governance,
    evaluate_platform_hardening_assessment,
    evaluate_pre_runtime_ga,
    evaluate_production_authority_readiness_review,
    evaluate_production_case_store_gate,
    evaluate_production_case_store_backend,
    evaluate_production_durable_case_store_readiness,
    evaluate_production_promotion_chain_readiness,
    evaluate_advisory_runtime_pilot,
    evaluate_release_promotion_execution_gate,
    evaluate_release_promotion_chain,
    evaluate_release_lifecycle,
    evaluate_repository_governance,
    evaluate_runtime_control_plane,
    evaluate_schema_stability,
    evaluate_api_architecture_contract,
    evaluate_adapter_evidence_contract,
    evaluate_governance_store_contract,
    evaluate_ml_shared_capability_inventory,
    evaluate_product_pack_foundation,
    evaluate_runtime_authority_blocked_model,
    evaluate_shared_service_certification,
    evaluate_shared_capability_certification_states,
    evaluate_v11_platform_foundation,
    evaluate_product_pack_contracts,
    evaluate_rest_api_contracts,
    evaluate_event_recovery_contract,
    evaluate_v15_api_foundation,
    evaluate_certification_evidence_packs,
    evaluate_product_pack_admission,
    evaluate_openapi_skeleton,
    evaluate_event_recovery_fixtures,
    evaluate_governance_store_logical_schema,
    evaluate_v20_architecture_closure,
    evaluate_canonical_openapi_contract,
    evaluate_product_pack_contract_kit,
    evaluate_adapter_evidence_contract_kit,
    evaluate_governance_store_logical_api,
    evaluate_event_recovery_contract_v2,
    evaluate_v25_contract_closure,
    evaluate_shared_capability_certification_workflow,
    evaluate_runtime_authority_gate_contract,
    evaluate_cost_usage_evidence_contract,
    evaluate_shared_context_semantic_projection_contract,
    evaluate_product_pack_developer_kit,
    evaluate_v30_platform_operating_model_closure,
    evaluate_contract_compatibility_versioning,
    evaluate_policy_test_pack_framework,
    evaluate_product_pack_cli_scaffold_contract,
    evaluate_case_evidence_query_contract,
    evaluate_governance_dashboard_data_contract,
    evaluate_v35_usability_governance_closure,
    evaluate_product_pack_authoring_ux_contract,
    evaluate_governance_review_queue_contract,
    evaluate_capability_lineage_explorer_contract,
    evaluate_replay_workspace_contract,
    evaluate_v40_usability_acceptance_pack,
    evaluate_evidence_retention_legal_hold_contract,
    evaluate_tenant_workspace_boundary_contract,
    evaluate_entitlement_usage_gate_contract,
    evaluate_integration_certification_ux_contract,
    evaluate_platform_operator_readiness_pack,
    evaluate_repository_governance_evidence_pack,
    evaluate_pr_validation_policy,
    evaluate_governance_exception_register,
    evaluate_edi_observer_ingestion_contract,
    evaluate_platform_governance_closure_pack,
    evaluate_shared_context_runtime_governance,
    evaluate_shared_context_governance,
    evaluate_solo_maintainer_exception,
    verify_case_manifest,
    write_v0_2_evidence,
)


class TrustLoopTests(unittest.TestCase):
    def test_default_examples_validate(self) -> None:
        result = validate_default_examples(ROOT)

        self.assertTrue(result["passed"])
        self.assertEqual(result["passed_count"], result["record_count"])

    def test_decision_spec_blocks_production_by_default(self) -> None:
        result = validate_file("decision_spec", ROOT / "examples/support-ticket-routing-decision-spec.json")

        self.assertTrue(result["passed"])

    def test_trust_loop_is_pre_runtime(self) -> None:
        payload = build_trust_loop(ROOT)

        self.assertTrue(payload["acceptance"]["trust_loop_complete"])
        self.assertFalse(payload["trust_loop_run"]["runtime_execution_requested"])
        self.assertTrue(payload["acceptance"]["computed_policy_engine_observed"])
        self.assertEqual(payload["acceptance"]["computed_policy_engine_result"], "approval_required")
        self.assertTrue(payload["acceptance"]["policy_engine_valid"])
        self.assertTrue(payload["acceptance"]["policy_engine_deny_precedence_enforced"])
        self.assertTrue(payload["acceptance"]["policy_engine_escalate_outcome_supported"])
        self.assertTrue(payload["acceptance"]["policy_engine_compatibility_valid"])
        self.assertTrue(payload["acceptance"]["computed_policy_preflight_observed"])
        self.assertTrue(payload["acceptance"]["computed_simulation_observed"])
        self.assertEqual(payload["acceptance"]["computed_simulation_case_count"], 13)
        self.assertEqual(payload["acceptance"]["computed_simulation_domain_count"], 3)
        self.assertTrue(payload["acceptance"]["computed_decision_diff_observed"])
        self.assertEqual(payload["acceptance"]["computed_decision_diff_changed_outcomes"], 3)
        self.assertTrue(payload["acceptance"]["case_manifest_valid"])
        self.assertTrue(payload["acceptance"]["durable_case_manifest_observed"])
        self.assertTrue(payload["acceptance"]["durable_case_manifest_valid"])
        self.assertFalse(payload["acceptance"]["case_mutation_detected"])
        self.assertTrue(payload["acceptance"]["approval_bound_to_manifest"])
        self.assertTrue(payload["acceptance"]["approval_role_binding_valid"])
        self.assertTrue(payload["acceptance"]["approval_authority_evaluated"])
        self.assertTrue(payload["acceptance"]["approval_authority_valid"])
        self.assertFalse(payload["acceptance"]["external_identity_provider_observed"])
        self.assertTrue(payload["acceptance"]["repository_governance_policy_observed"])
        self.assertTrue(payload["acceptance"]["admin_enforcement_required"])
        self.assertTrue(payload["acceptance"]["break_glass_policy_defined"])
        self.assertTrue(payload["acceptance"]["release_lifecycle_policy_observed"])
        self.assertTrue(payload["acceptance"]["release_lifecycle_valid"])
        self.assertTrue(payload["acceptance"]["external_identity_contract_observed"])
        self.assertTrue(payload["acceptance"]["external_identity_contract_valid"])
        self.assertFalse(payload["acceptance"]["live_external_identity_provider_authenticated"])
        self.assertTrue(payload["acceptance"]["live_identity_rbac_observed"])
        self.assertTrue(payload["acceptance"]["live_identity_rbac_valid"])
        self.assertTrue(payload["acceptance"]["live_identity_rbac_permission_sufficient"])
        self.assertTrue(payload["acceptance"]["live_identity_rbac_decision_scope_authorized"])
        self.assertFalse(payload["acceptance"]["live_identity_rbac_mfa_claim_observed"])
        self.assertTrue(payload["acceptance"]["durable_evidence_store_policy_observed"])
        self.assertTrue(payload["acceptance"]["durable_store_contract_valid"])
        self.assertFalse(payload["acceptance"]["production_storage_backend_observed"])
        self.assertTrue(payload["acceptance"]["capability_governance_observed"])
        self.assertTrue(payload["acceptance"]["capability_governance_valid"])
        self.assertTrue(payload["acceptance"]["shared_context_contract_observed"])
        self.assertTrue(payload["acceptance"]["shared_context_contract_valid"])
        self.assertTrue(payload["acceptance"]["solo_maintainer_exception_observed"])
        self.assertTrue(payload["acceptance"]["solo_maintainer_exception_valid"])
        self.assertFalse(payload["acceptance"]["independent_human_review_observed"])
        self.assertTrue(payload["acceptance"]["schema_stability_observed"])
        self.assertTrue(payload["acceptance"]["schema_stability_valid"])
        self.assertTrue(payload["acceptance"]["negative_fixtures_valid"])
        self.assertTrue(payload["acceptance"]["external_approval_boundary_observed"])
        self.assertTrue(payload["acceptance"]["external_approval_boundary_valid"])
        self.assertFalse(payload["acceptance"]["live_external_approval_system_observed"])
        self.assertTrue(payload["acceptance"]["decision_approval_separate_from_code_merge"])
        self.assertTrue(payload["acceptance"]["durable_case_store_adapter_observed"])
        self.assertTrue(payload["acceptance"]["durable_case_store_adapter_valid"])
        self.assertFalse(payload["acceptance"]["adapter_production_storage_backend_observed"])
        self.assertTrue(payload["acceptance"]["evidence_store_adapter_parity_observed"])
        self.assertTrue(payload["acceptance"]["evidence_store_adapter_parity_valid"])
        self.assertFalse(payload["acceptance"]["adapter_runtime_backend_invoked"])
        self.assertTrue(payload["acceptance"]["durable_evidence_backend_observed"])
        self.assertTrue(payload["acceptance"]["durable_evidence_backend_valid"])
        self.assertFalse(payload["acceptance"]["durable_backend_runtime_backend_invoked"])
        self.assertTrue(payload["acceptance"]["release_promotion_chain_observed"])
        self.assertTrue(payload["acceptance"]["release_promotion_chain_valid"])
        self.assertFalse(payload["acceptance"]["prod_deployment_executed"])
        self.assertTrue(payload["acceptance"]["pre_runtime_ga_observed"])
        self.assertTrue(payload["acceptance"]["pre_runtime_ga_valid"])
        self.assertTrue(payload["acceptance"]["v3_1_governance_closure_valid"])
        self.assertTrue(payload["acceptance"]["v3_2_external_identity_boundary_valid"])
        self.assertFalse(payload["acceptance"]["v3_2_external_identity_live_ready"])
        self.assertFalse(payload["acceptance"]["v3_2_mfa_claim_observed"])
        self.assertTrue(payload["acceptance"]["v3_3_external_approval_system_boundary_valid"])
        self.assertFalse(payload["acceptance"]["v3_3_external_approval_system_live_ready"])
        self.assertTrue(payload["acceptance"]["v3_4_production_case_store_contract_ready"])
        self.assertFalse(payload["acceptance"]["v3_4_production_case_store_live_ready"])
        self.assertTrue(payload["acceptance"]["v3_5_runtime_control_plane_design_valid"])
        self.assertFalse(payload["acceptance"]["v3_5_runtime_authority_grant_allowed"])
        self.assertTrue(payload["acceptance"]["v3_6_advisory_runtime_pilot_valid"])
        self.assertFalse(payload["acceptance"]["v3_6_advisory_side_effects_executed"])
        self.assertTrue(payload["acceptance"]["v4_0_limited_runtime_authority_gate_complete"])
        self.assertFalse(payload["acceptance"]["v4_0_limited_runtime_authority_granted"])
        self.assertTrue(payload["acceptance"]["v4_1_live_identity_evidence_gate_complete"])
        self.assertFalse(payload["acceptance"]["v4_1_live_identity_authority_ready"])
        self.assertFalse(payload["acceptance"]["v4_1_mfa_claim_observed"])
        self.assertTrue(payload["acceptance"]["v4_2_live_approval_provider_gate_complete"])
        self.assertFalse(payload["acceptance"]["v4_2_live_approval_provider_ready"])
        self.assertFalse(payload["acceptance"]["v4_2_ai_approval_allowed"])
        self.assertTrue(payload["acceptance"]["v4_3_production_case_store_gate_complete"])
        self.assertFalse(payload["acceptance"]["v4_3_production_case_store_live_ready"])
        self.assertTrue(payload["acceptance"]["v4_4_release_promotion_execution_gate_complete"])
        self.assertFalse(payload["acceptance"]["v4_4_prod_deployment_executed"])
        self.assertTrue(payload["acceptance"]["v5_0_governed_advisory_runtime_complete"])
        self.assertTrue(payload["acceptance"]["v5_0_runtime_recommendation_only"])
        self.assertFalse(payload["acceptance"]["v5_0_side_effects_executed"])
        self.assertTrue(payload["acceptance"]["v5_5_controlled_runtime_execution_gate_complete"])
        self.assertFalse(payload["acceptance"]["v5_5_controlled_runtime_execution_authorized"])
        self.assertTrue(payload["acceptance"]["v6_0_platform_hardening_assessment_complete"])
        self.assertFalse(payload["acceptance"]["v6_0_platform_production_ready"])
        self.assertTrue(payload["acceptance"]["v10_0_completion_plan_execution_observed"])
        self.assertTrue(payload["acceptance"]["v10_0_autopilot_execution_review_complete"])
        self.assertEqual(payload["acceptance"]["v10_0_reviewed_step_count"], 9)
        self.assertEqual(payload["acceptance"]["v10_0_evidence_gate_complete_count"], 9)
        self.assertGreaterEqual(payload["acceptance"]["v10_0_blocked_live_completion_count"], 8)
        self.assertTrue(payload["acceptance"]["v10_0_product_vision_alignment_valid"])
        self.assertTrue(payload["acceptance"]["v10_0_runtime_authority_grant_blocked"])
        self.assertTrue(payload["acceptance"]["v10_0_production_decision_authority_blocked"])
        self.assertTrue(payload["acceptance"]["runtime_readiness_assessment_observed"])
        self.assertEqual(payload["acceptance"]["runtime_readiness_percent"], 0.0)
        self.assertTrue(payload["acceptance"]["product_review_surface_observed"])
        self.assertGreaterEqual(payload["acceptance"]["product_review_surface_count"], 8)
        self.assertFalse(payload["acceptance"]["runtime_integration_authorized"])
        self.assertFalse(payload["acceptance"]["production_decision_execution_authorized"])

    def test_write_trust_loop_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp)
            write_trust_loop(out, ROOT)

            acceptance = json.loads((out / "dip-mvp-acceptance.json").read_text(encoding="utf-8"))
            self.assertTrue(acceptance["trust_loop_complete"])
            self.assertTrue(acceptance["durable_case_manifest_valid"])
            self.assertTrue(acceptance["approval_bound_to_manifest"])
            self.assertTrue(acceptance["approval_authority_valid"])
            self.assertFalse(acceptance["runtime_integration_authorized"])

    def test_v0_2_computes_policy_preflight(self) -> None:
        payload = compute_policy_preflight(ROOT)

        self.assertTrue(payload["computed"])
        self.assertEqual(payload["result"], "approval_required")
        self.assertFalse(payload["ai_override_allowed"])
        self.assertIn("support-platform-owner", payload["required_approvals"])

    def test_v2_5_computes_policy_engine_with_lifecycle_and_precedence(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        engine = compute_policy_engine(ROOT)

        self.assertTrue(engine["computed"])
        self.assertEqual(engine["result"], "approval_required")
        self.assertEqual(engine["policy_set_version"], "2.5.0-pre")
        self.assertGreaterEqual(engine["supported_rule_type_count"], 5)
        self.assertGreaterEqual(engine["active_policy_count"], 5)
        self.assertEqual(engine["revoked_policy_count"], 0)
        self.assertTrue(engine["deny_precedence_enforced"])
        self.assertTrue(engine["escalate_outcome_supported"])
        self.assertTrue(engine["policy_compatibility_valid"])
        self.assertTrue(engine["policy_engine_valid"])
        self.assertFalse(engine["ai_override_allowed"])
        self.assertFalse(engine["runtime_integration_authorized"])
        self.assertFalse(engine["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["computed_policy_engine_observed"])
        self.assertEqual(result["release"]["computed_policy_engine_result"], "approval_required")
        self.assertTrue(result["release"]["policy_engine_valid"])
        self.assertTrue(result["release"]["policy_engine_deny_precedence_enforced"])
        self.assertTrue(result["release"]["policy_engine_escalate_outcome_supported"])
        self.assertTrue(result["release"]["policy_engine_compatibility_valid"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v0_4_computes_simulation_from_explicit_case_inputs(self) -> None:
        payload = compute_simulation(ROOT)

        self.assertTrue(payload["computed"])
        self.assertEqual(payload["case_count"], 13)
        self.assertEqual(payload["domain_count"], 3)
        self.assertEqual(payload["decision_shape_count"], 3)
        self.assertEqual(payload["changed_outcome_count"], 3)
        self.assertFalse(payload["runtime_execution_requested"])
        self.assertFalse(payload["production_decision_execution_authorized"])
        self.assertIn(
            "hold_for_governance_review",
            [record["decision_output"] for record in payload["engineering_review_results"]],
        )
        self.assertIn(
            "escalate_to_risk_owner",
            [record["decision_output"] for record in payload["operational_risk_results"]],
        )

    def test_v0_5_computes_decision_diff_from_simulation(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        payload = result["decision_diff"]

        self.assertTrue(payload["computed"])
        self.assertEqual(payload["from_decision_version"], "0.9.0")
        self.assertEqual(payload["to_decision_version"], "1.0.0")
        self.assertIn("decision_logic_changed", payload["spec_changes"])
        self.assertEqual(payload["changed_outcome_count"], 3)
        self.assertTrue(payload["simulation_computed"])
        self.assertEqual(payload["simulation_case_count"], 13)
        self.assertFalse(payload["runtime_execution_requested"])

    def test_v0_5_manifest_approval_and_release_pack_are_pre_runtime(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            write_trust_loop(Path(tmp), ROOT)
            result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

            self.assertTrue(verify_case_manifest(ROOT, result["manifest"]))
            self.assertTrue(verify_case_manifest(ROOT, result["durable_manifest"]))
            self.assertFalse(result["durable_manifest"]["mutation_detected"])
            self.assertTrue(result["approval"]["approval_bound_to_manifest"])
            self.assertEqual(result["approval"]["case_manifest_hash"], result["durable_manifest"]["manifest_hash"])
            self.assertTrue(result["approval"]["role_binding_valid"])
            self.assertTrue(result["replay"]["manifest_replay_valid"])
            self.assertTrue(result["release"]["computed_simulation_observed"])
            self.assertEqual(result["release"]["computed_simulation_case_count"], 13)
            self.assertEqual(result["release"]["computed_simulation_domain_count"], 3)
            self.assertEqual(result["release"]["computed_simulation_decision_shape_count"], 3)
            self.assertTrue(result["release"]["computed_decision_diff_observed"])
            self.assertEqual(result["release"]["computed_decision_diff_changed_outcomes"], 3)
            self.assertTrue(result["release"]["durable_case_manifest_valid"])
            self.assertTrue(result["release"]["append_only_chain_valid"])
            self.assertFalse(result["release"]["case_mutation_detected"])
            self.assertTrue(result["release"]["replay_from_manifest_observed"])
            self.assertTrue(result["release"]["approval_bound_to_manifest"])
            self.assertTrue(result["release"]["approval_role_binding_valid"])
            self.assertTrue(result["release"]["repository_governance_policy_observed"])
            self.assertTrue(result["release"]["admin_enforcement_required"])
            self.assertTrue(result["release"]["break_glass_policy_defined"])
            self.assertTrue(result["release"]["release_lifecycle_valid"])
            self.assertTrue(result["release"]["external_identity_contract_valid"])
            self.assertTrue(result["release"]["durable_store_contract_valid"])
            self.assertTrue(result["release"]["capability_governance_valid"])
            self.assertTrue(result["release"]["shared_context_contract_valid"])
            self.assertTrue(result["release"]["solo_maintainer_exception_valid"])
            self.assertFalse(result["release"]["independent_human_review_observed"])
            self.assertTrue(result["release"]["schema_stability_valid"])
            self.assertTrue(result["release"]["negative_fixtures_valid"])
            self.assertTrue(result["release"]["external_approval_boundary_valid"])
            self.assertFalse(result["release"]["live_external_approval_system_observed"])
            self.assertTrue(result["release"]["decision_approval_separate_from_code_merge"])
            self.assertTrue(result["release"]["durable_case_store_adapter_observed"])
            self.assertTrue(result["release"]["durable_case_store_adapter_valid"])
            self.assertFalse(result["release"]["adapter_production_storage_backend_observed"])
            self.assertTrue(result["release"]["adapter_append_only_writes_required"])
            self.assertTrue(result["release"]["adapter_content_addressed_records_required"])
            self.assertTrue(result["release"]["adapter_delete_denied_required"])
            self.assertTrue(result["release"]["adapter_mutation_detection_required"])
            self.assertTrue(result["release"]["adapter_replay_export_required"])
            self.assertTrue(result["release"]["adapter_audit_export_required"])
            self.assertTrue(result["release"]["adapter_retention_policy_valid"])
            self.assertTrue(result["release"]["adapter_required_operations_complete"])
            self.assertTrue(result["release"]["adapter_denied_operations_complete"])
            self.assertTrue(result["release"]["evidence_store_adapter_parity_observed"])
            self.assertTrue(result["release"]["evidence_store_adapter_parity_valid"])
            self.assertTrue(result["release"]["adapter_required_operations_valid"])
            self.assertTrue(result["release"]["adapter_denied_operations_enforced"])
            self.assertTrue(result["release"]["adapter_append_case_record_valid"])
            self.assertTrue(result["release"]["adapter_read_case_record_valid"])
            self.assertTrue(result["release"]["adapter_verify_manifest_chain_valid"])
            self.assertTrue(result["release"]["adapter_export_replay_pack_valid"])
            self.assertTrue(result["release"]["adapter_export_audit_pack_valid"])
            self.assertFalse(result["release"]["adapter_runtime_backend_invoked"])
            self.assertTrue(result["release"]["durable_evidence_backend_observed"])
            self.assertTrue(result["release"]["durable_evidence_backend_valid"])
            self.assertFalse(result["release"]["durable_backend_runtime_backend_invoked"])
            self.assertFalse(result["release"]["durable_backend_production_storage_backend_observed"])
            self.assertTrue(result["release"]["release_promotion_chain_observed"])
            self.assertTrue(result["release"]["release_promotion_chain_valid"])
            self.assertTrue(result["release"]["immutable_artifact_digest_observed"])
            self.assertTrue(result["release"]["source_commit_bound"])
            self.assertTrue(result["release"]["build_run_id_observed"])
            self.assertTrue(result["release"]["rollback_evidence_valid"])
            self.assertFalse(result["release"]["prod_deployment_executed"])
            self.assertTrue(result["release"]["pre_runtime_ga_observed"])
            self.assertTrue(result["release"]["pre_runtime_ga_valid"])
            self.assertEqual(result["release"]["pre_runtime_ga_status_label"], "pre_runtime_ga_complete_runtime_blocked")
            self.assertEqual(result["release"]["runtime_readiness_percent"], 0.0)
            self.assertEqual(result["release"]["production_decision_authority_percent"], 0.0)
            self.assertTrue(result["release"]["product_review_surface_observed"])
            self.assertTrue(result["release"]["release_acceptance_passed"])
            self.assertFalse(result["release"]["runtime_integration_authorized"])
            self.assertFalse(result["release"]["production_decision_execution_authorized"])

    def test_v0_6_evaluates_identity_rbac_approval_authority_without_external_idp(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        authority = evaluate_approval_authority(ROOT, result["durable_manifest"])

        self.assertTrue(authority["computed"])
        self.assertEqual(authority["source_boundary"], "versioned_local_registry_not_external_idp")
        self.assertTrue(authority["approval_authority_valid"])
        self.assertTrue(authority["identity_active"])
        self.assertTrue(authority["identity_not_expired"])
        self.assertTrue(authority["mfa_satisfied"])
        self.assertTrue(authority["decision_scope_authorized"])
        self.assertTrue(authority["ai_self_approval_blocked"])
        self.assertEqual(authority["approver_subject"], "Raghurammutya@gmail.com")
        self.assertFalse(authority["external_identity_provider_observed"])
        self.assertTrue(result["release"]["approval_authority_evaluated"])
        self.assertTrue(result["release"]["approval_authority_valid"])
        self.assertTrue(result["release"]["ai_self_approval_blocked"])
        self.assertFalse(result["release"]["external_identity_provider_observed"])

    def test_v0_7_defines_repository_governance_policy_without_runtime_authority(self) -> None:
        governance = evaluate_repository_governance(ROOT)
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

        self.assertTrue(governance["computed"])
        self.assertEqual(governance["source_boundary"], "declared_repository_governance_policy_not_runtime_execution")
        self.assertTrue(governance["admin_enforcement_required"])
        self.assertEqual(governance["required_status_checks"], ["validate"])
        self.assertEqual(governance["required_approving_review_count"], 1)
        self.assertTrue(governance["branch_protection_observed"])
        self.assertTrue(governance["required_status_checks_observed"])
        self.assertGreaterEqual(governance["required_approving_review_count_observed"], 1)
        self.assertTrue(governance["codeowner_review_required_observed"])
        self.assertTrue(governance["conversation_resolution_required_observed"])
        self.assertTrue(governance["admin_enforcement_observed"])
        self.assertTrue(governance["force_pushes_blocked"])
        self.assertTrue(governance["deletions_blocked"])
        self.assertTrue(governance["break_glass_policy_defined"])
        self.assertFalse(governance["runtime_integration_authorized"])
        self.assertFalse(governance["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["repository_governance_policy_observed"])
        self.assertTrue(result["release"]["admin_enforcement_required"])
        self.assertTrue(result["release"]["required_status_checks_observed"])
        self.assertTrue(result["release"]["codeowner_review_required_observed"])
        self.assertTrue(result["release"]["conversation_resolution_required_observed"])
        self.assertTrue(result["release"]["break_glass_policy_defined"])

    def test_v0_8_defines_release_lifecycle_without_runtime_authority(self) -> None:
        lifecycle = evaluate_release_lifecycle(ROOT)
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

        self.assertTrue(lifecycle["computed"])
        self.assertEqual(lifecycle["stage_count"], 6)
        self.assertTrue(lifecycle["release_lifecycle_valid"])
        self.assertTrue(lifecycle["independent_approval_required"])
        self.assertTrue(lifecycle["codeowner_review_required"])
        self.assertTrue(lifecycle["conversation_resolution_required"])
        self.assertGreaterEqual(lifecycle["rollback_criteria_count"], 3)
        self.assertFalse(lifecycle["runtime_integration_authorized"])
        self.assertTrue(result["release"]["release_lifecycle_policy_observed"])
        self.assertTrue(result["release"]["release_lifecycle_valid"])

    def test_v0_9_defines_external_identity_contract_without_live_auth(self) -> None:
        external = evaluate_external_identity(ROOT)
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

        self.assertTrue(external["computed"])
        self.assertEqual(external["source_boundary"], "external_idp_contract_evidence_not_live_authentication")
        self.assertTrue(external["external_identity_contract_valid"])
        self.assertTrue(external["required_claims_present"])
        self.assertTrue(external["approval_identity_bound_to_subject"])
        self.assertFalse(external["live_provider_authenticated"])
        self.assertTrue(result["release"]["external_identity_contract_observed"])
        self.assertTrue(result["release"]["external_identity_contract_valid"])
        self.assertFalse(result["release"]["live_external_identity_provider_authenticated"])

    def test_v2_7_observes_live_identity_rbac_without_mfa_claim(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        live = evaluate_live_identity_rbac(ROOT)

        self.assertTrue(live["computed"])
        self.assertEqual(live["provider"], "github")
        self.assertTrue(live["live_provider_authenticated"])
        self.assertTrue(live["repository_permission_observed"])
        self.assertTrue(live["permission_satisfies_approval_role"])
        self.assertTrue(live["decision_scope_authorized"])
        self.assertFalse(live["mfa_claim_observed"])
        self.assertTrue(live["live_identity_rbac_valid"])
        self.assertFalse(live["runtime_integration_authorized"])
        self.assertFalse(live["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["live_identity_rbac_observed"])
        self.assertTrue(result["release"]["live_identity_rbac_valid"])
        self.assertTrue(result["release"]["live_identity_rbac_permission_sufficient"])
        self.assertTrue(result["release"]["live_identity_rbac_decision_scope_authorized"])
        self.assertFalse(result["release"]["live_identity_rbac_mfa_claim_observed"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v1_0_defines_durable_store_contract_without_production_storage(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        durable_store = evaluate_durable_evidence_store(ROOT, result["durable_manifest"])

        self.assertTrue(durable_store["computed"])
        self.assertEqual(durable_store["storage_model"], "append_only_content_addressed_log")
        self.assertTrue(durable_store["required_controls_present"])
        self.assertTrue(durable_store["content_addressed_records"])
        self.assertTrue(durable_store["manifest_hash_chain"])
        self.assertTrue(durable_store["append_only_enforced_by_contract"])
        self.assertTrue(durable_store["delete_denied_by_contract"])
        self.assertFalse(durable_store["production_storage_backend_observed"])
        self.assertTrue(result["release"]["durable_evidence_store_policy_observed"])
        self.assertTrue(result["release"]["durable_store_contract_valid"])
        self.assertFalse(result["release"]["production_storage_backend_observed"])

    def test_v1_4_evaluates_capability_governance_without_runtime_invocation(self) -> None:
        capability = evaluate_capability_governance(ROOT)
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

        self.assertTrue(capability["computed"])
        self.assertEqual(capability["decision_count"], 3)
        self.assertEqual(capability["resolved_capability_count"], 3)
        self.assertTrue(capability["exact_versions_resolved"])
        self.assertTrue(capability["provenance_recorded"])
        self.assertTrue(capability["entitlements_recorded"])
        self.assertTrue(capability["compatibility_recorded"])
        self.assertTrue(capability["evaluation_evidence_recorded"])
        self.assertTrue(capability["cost_profiles_recorded"])
        self.assertTrue(capability["capability_governance_valid"])
        self.assertFalse(capability["runtime_integration_authorized"])
        self.assertTrue(result["release"]["capability_governance_observed"])
        self.assertTrue(result["release"]["capability_governance_valid"])

    def test_v1_5_evaluates_shared_context_contract_without_runtime_exchange(self) -> None:
        shared_context = evaluate_shared_context_governance(ROOT)
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

        self.assertTrue(shared_context["computed"])
        self.assertTrue(shared_context["purpose_declared"])
        self.assertTrue(shared_context["ttl_declared"])
        self.assertTrue(shared_context["masking_rules_declared"])
        self.assertTrue(shared_context["approval_required"])
        self.assertTrue(shared_context["source_lineage_declared"])
        self.assertTrue(shared_context["freshness_rules_declared"])
        self.assertTrue(shared_context["policy_decision_evidence_declared"])
        self.assertFalse(shared_context["direct_database_access_allowed"])
        self.assertFalse(shared_context["runtime_context_exchange_authorized"])
        self.assertTrue(shared_context["shared_context_contract_valid"])
        self.assertTrue(result["release"]["shared_context_contract_observed"])
        self.assertTrue(result["release"]["shared_context_contract_valid"])

    def test_v2_1_records_solo_maintainer_exception_without_review_overclaim(self) -> None:
        exception = evaluate_solo_maintainer_exception(ROOT)
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

        self.assertTrue(exception["computed"])
        self.assertTrue(exception["solo_maintainer_constraint"])
        self.assertFalse(exception["independent_human_review_available"])
        self.assertFalse(exception["independent_human_review_observed"])
        self.assertTrue(exception["review_relaxation_allowed"])
        self.assertTrue(exception["required_controls_present"])
        self.assertTrue(exception["restored_protection_required"])
        self.assertTrue(exception["independent_review_claim_blocked"])
        self.assertTrue(exception["exception_valid"])
        self.assertFalse(exception["runtime_integration_authorized"])
        self.assertTrue(result["release"]["solo_maintainer_exception_observed"])
        self.assertTrue(result["release"]["solo_maintainer_exception_valid"])
        self.assertFalse(result["release"]["independent_human_review_observed"])
        self.assertTrue(result["release"]["review_relaxation_allowed"])
        self.assertTrue(result["release"]["review_gate_restoration_required"])

    def test_v2_1_validates_schema_stability_and_negative_fixtures(self) -> None:
        stability = evaluate_schema_stability(ROOT)
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

        self.assertTrue(stability["computed"])
        self.assertGreaterEqual(stability["frozen_contract_count"], 19)
        self.assertTrue(stability["frozen_contracts_valid"])
        self.assertGreaterEqual(stability["compatibility_rule_count"], 5)
        self.assertEqual(stability["negative_fixture_count"], 12)
        self.assertTrue(stability["negative_fixtures_valid"])
        self.assertTrue(stability["schema_stability_valid"])
        self.assertFalse(stability["runtime_integration_authorized"])
        self.assertTrue(result["release"]["schema_stability_observed"])
        self.assertTrue(result["release"]["schema_stability_valid"])
        self.assertTrue(result["release"]["negative_fixtures_valid"])

    def test_v2_2_separates_external_approval_from_github_review_exception(self) -> None:
        boundary = evaluate_external_approval_boundary(ROOT)
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")

        self.assertTrue(boundary["computed"])
        self.assertTrue(boundary["decision_approval_required"])
        self.assertFalse(boundary["live_approval_system_observed"])
        self.assertFalse(boundary["github_code_review_is_decision_approval"])
        self.assertFalse(boundary["solo_maintainer_exception_is_decision_approval"])
        self.assertTrue(boundary["decision_approval_separate_from_code_merge"])
        self.assertTrue(boundary["approval_subject_binding_required"])
        self.assertTrue(boundary["approval_role_scope_required"])
        self.assertTrue(boundary["approval_expiry_required"])
        self.assertTrue(boundary["approval_mfa_required"])
        self.assertTrue(boundary["approval_audit_export_required"])
        self.assertFalse(boundary["ai_approval_allowed"])
        self.assertTrue(boundary["required_evidence_complete"])
        self.assertTrue(boundary["admission_controls_complete"])
        self.assertTrue(boundary["external_approval_boundary_valid"])
        self.assertFalse(boundary["runtime_integration_authorized"])
        self.assertTrue(result["release"]["external_approval_boundary_observed"])
        self.assertTrue(result["release"]["external_approval_boundary_valid"])
        self.assertFalse(result["release"]["live_external_approval_system_observed"])
        self.assertTrue(result["release"]["decision_approval_separate_from_code_merge"])

    def test_v2_6_defines_external_approval_adapter_boundary_without_live_system(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        adapter = evaluate_external_approval_adapter(ROOT)

        self.assertTrue(adapter["computed"])
        self.assertEqual(adapter["source_boundary"], "adapter_contract_not_live_approval_system")
        self.assertEqual(adapter["adapter_type"], "contract_only")
        self.assertFalse(adapter["live_approval_system_observed"])
        self.assertFalse(adapter["github_code_review_is_decision_approval"])
        self.assertFalse(adapter["solo_maintainer_exception_is_decision_approval"])
        self.assertFalse(adapter["ai_approval_allowed"])
        self.assertTrue(adapter["required_operations_complete"])
        self.assertTrue(adapter["denied_operations_complete"])
        self.assertTrue(adapter["request_evidence_fields_complete"])
        self.assertTrue(adapter["decision_evidence_fields_complete"])
        self.assertTrue(adapter["decision_lifecycle_complete"])
        self.assertTrue(adapter["admission_controls_complete"])
        self.assertTrue(adapter["audit_requirements_complete"])
        self.assertTrue(adapter["boundary_compatible"])
        self.assertTrue(adapter["external_approval_adapter_valid"])
        self.assertFalse(adapter["runtime_integration_authorized"])
        self.assertFalse(adapter["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["external_approval_adapter_observed"])
        self.assertTrue(result["release"]["external_approval_adapter_valid"])
        self.assertFalse(result["release"]["external_approval_adapter_live_system_observed"])
        self.assertFalse(result["release"]["external_approval_adapter_ai_approval_allowed"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v2_3_defines_durable_case_store_adapter_without_production_backend(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        adapter = evaluate_durable_case_store_adapter(ROOT, result["durable_manifest"])

        self.assertTrue(adapter["computed"])
        self.assertEqual(adapter["source_boundary"], "adapter_contract_not_production_storage_backend")
        self.assertEqual(adapter["storage_backend_type"], "contract_only")
        self.assertFalse(adapter["production_storage_backend_observed"])
        self.assertTrue(adapter["append_only_writes_required"])
        self.assertTrue(adapter["content_addressed_records_required"])
        self.assertTrue(adapter["manifest_hash_chain_required"])
        self.assertTrue(adapter["delete_denied_required"])
        self.assertTrue(adapter["mutation_detection_required"])
        self.assertTrue(adapter["retention_policy_required"])
        self.assertTrue(adapter["replay_export_required"])
        self.assertTrue(adapter["audit_export_required"])
        self.assertTrue(adapter["multi_writer_concurrency_control_required"])
        self.assertTrue(adapter["encryption_boundary_required"])
        self.assertTrue(adapter["tenant_namespace_required"])
        self.assertTrue(adapter["required_operations_complete"])
        self.assertTrue(adapter["denied_operations_complete"])
        self.assertTrue(adapter["retention_policy_valid"])
        self.assertTrue(adapter["manifest_hash_bound"])
        self.assertTrue(adapter["adapter_boundary_valid"])
        self.assertFalse(adapter["runtime_integration_authorized"])
        self.assertFalse(adapter["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["durable_case_store_adapter_observed"])
        self.assertTrue(result["release"]["durable_case_store_adapter_valid"])
        self.assertFalse(result["release"]["adapter_production_storage_backend_observed"])
        self.assertTrue(result["release"]["adapter_required_operations_complete"])
        self.assertTrue(result["release"]["adapter_denied_operations_complete"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v2_4_evaluates_evidence_store_adapter_parity_without_runtime_backend(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        parity = evaluate_evidence_store_adapter_parity(ROOT, result["durable_manifest"], result["replay"])

        self.assertTrue(parity["computed"])
        self.assertTrue(parity["required_operations_valid"])
        self.assertTrue(parity["denied_operations_enforced"])
        self.assertEqual(parity["required_operation_count"], 5)
        self.assertEqual(parity["denied_operation_count"], 3)
        self.assertTrue(parity["append_case_record_valid"])
        self.assertTrue(parity["read_case_record_valid"])
        self.assertTrue(parity["verify_manifest_chain_valid"])
        self.assertTrue(parity["export_replay_pack_valid"])
        self.assertTrue(parity["export_audit_pack_valid"])
        self.assertFalse(parity["runtime_backend_invoked"])
        self.assertFalse(parity["production_storage_backend_observed"])
        self.assertTrue(parity["adapter_parity_valid"])
        self.assertFalse(parity["runtime_integration_authorized"])
        self.assertFalse(parity["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["evidence_store_adapter_parity_observed"])
        self.assertTrue(result["release"]["evidence_store_adapter_parity_valid"])
        self.assertFalse(result["release"]["adapter_runtime_backend_invoked"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v2_8_observes_durable_evidence_backend_without_runtime_backend(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        backend = evaluate_durable_evidence_backend(ROOT, result["durable_manifest"], result["replay"])

        self.assertTrue(backend["computed"])
        self.assertEqual(backend["backend_type"], "local_append_only_evidence_backend")
        self.assertTrue(backend["append_only_case_write_observed"])
        self.assertTrue(backend["content_addressed_record_observed"])
        self.assertTrue(backend["manifest_chain_verification_from_backend"])
        self.assertTrue(backend["read_case_record_from_backend"])
        self.assertTrue(backend["replay_export_from_backend"])
        self.assertTrue(backend["audit_export_from_backend"])
        self.assertTrue(backend["delete_denied_observed"])
        self.assertTrue(backend["mutation_denied_observed"])
        self.assertTrue(backend["retention_policy_observed"])
        self.assertTrue(backend["durable_evidence_backend_valid"])
        self.assertFalse(backend["runtime_backend_invoked"])
        self.assertFalse(backend["production_storage_backend_observed"])
        self.assertTrue(result["release"]["durable_evidence_backend_valid"])
        self.assertFalse(result["release"]["durable_backend_runtime_backend_invoked"])

    def test_v2_9_observes_release_promotion_chain_without_prod_deployment(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        promotion = evaluate_release_promotion_chain(ROOT, "v10.0.0-pre", "local-validation")

        self.assertTrue(promotion["computed"])
        self.assertTrue(promotion["immutable_artifact_digest_observed"])
        self.assertTrue(promotion["source_commit_bound"])
        self.assertTrue(promotion["build_run_id_observed"])
        self.assertTrue(promotion["promotion_chain_declared"])
        self.assertEqual(promotion["promotion_stages"], ["dev", "test", "staging", "prod"])
        self.assertTrue(promotion["promotion_approval_record_observed"])
        self.assertTrue(promotion["rollback_evidence_valid"])
        self.assertTrue(promotion["solo_maintainer_exception_recorded"])
        self.assertFalse(promotion["independent_human_review_observed"])
        self.assertFalse(promotion["prod_deployment_executed"])
        self.assertTrue(promotion["release_promotion_chain_valid"])
        self.assertTrue(result["release"]["release_promotion_chain_valid"])
        self.assertFalse(result["release"]["prod_deployment_executed"])

    def test_v3_0_pre_runtime_ga_complete_runtime_blocked(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        ga = evaluate_pre_runtime_ga(ROOT)

        self.assertTrue(ga["computed"])
        self.assertTrue(ga["governed_decision_review_and_simulation_complete"])
        self.assertTrue(ga["trust_surface_complete"])
        self.assertTrue(ga["policy_engine_complete"])
        self.assertTrue(ga["simulation_diff_complete"])
        self.assertTrue(ga["approval_boundary_complete"])
        self.assertTrue(ga["durable_evidence_backend_observed"])
        self.assertTrue(ga["promotion_chain_rollback_observed"])
        self.assertFalse(ga["live_identity_mfa_claim_observed"])
        self.assertEqual(ga["runtime_execution_readiness_percent"], 0.0)
        self.assertEqual(ga["production_decision_authority_percent"], 0.0)
        self.assertTrue(ga["runtime_blocked"])
        self.assertTrue(ga["pre_runtime_ga_valid"])
        self.assertTrue(result["release"]["pre_runtime_ga_valid"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v3_1_to_v4_0_completes_authority_gate_without_granting_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        governance = evaluate_governance_closure(ROOT)
        identity = evaluate_external_identity_integration(ROOT)
        approval = evaluate_external_approval_system(ROOT)
        case_store = evaluate_production_case_store_backend(ROOT)
        control_plane = evaluate_runtime_control_plane(ROOT)
        advisory = evaluate_advisory_runtime_pilot(ROOT)
        authority = evaluate_limited_runtime_authority_gate(ROOT)

        self.assertTrue(governance["governance_closure_valid"])
        self.assertFalse(governance["independent_human_review_observed"])
        self.assertTrue(identity["external_identity_boundary_valid"])
        self.assertFalse(identity["external_identity_live_ready"])
        self.assertFalse(identity["mfa_claim_observed"])
        self.assertTrue(approval["external_approval_system_boundary_valid"])
        self.assertFalse(approval["external_approval_system_live_ready"])
        self.assertFalse(approval["ai_approval_allowed"])
        self.assertTrue(case_store["production_case_store_contract_ready"])
        self.assertFalse(case_store["production_case_store_live_ready"])
        self.assertFalse(case_store["production_storage_backend_observed"])
        self.assertTrue(control_plane["runtime_control_plane_design_valid"])
        self.assertFalse(control_plane["runtime_authority_grant_allowed"])
        self.assertTrue(advisory["advisory_runtime_pilot_valid"])
        self.assertFalse(advisory["side_effects_executed"])
        self.assertFalse(advisory["production_mutation_executed"])
        self.assertTrue(authority["limited_runtime_authority_gate_complete"])
        self.assertFalse(authority["limited_runtime_authority_granted"])
        self.assertIn("live_external_idp_mfa_ready", authority["blocked_reasons"])
        self.assertIn("live_external_approval_system_ready", authority["blocked_reasons"])
        self.assertIn("production_case_store_live_ready", authority["blocked_reasons"])
        self.assertEqual(authority["runtime_execution_readiness_percent"], 0.0)
        self.assertEqual(authority["production_decision_authority_percent"], 0.0)
        self.assertTrue(result["release"]["v3_1_governance_closure_valid"])
        self.assertTrue(result["release"]["v3_2_external_identity_boundary_valid"])
        self.assertFalse(result["release"]["v3_2_external_identity_live_ready"])
        self.assertTrue(result["release"]["v3_3_external_approval_system_boundary_valid"])
        self.assertFalse(result["release"]["v3_3_external_approval_system_live_ready"])
        self.assertTrue(result["release"]["v3_4_production_case_store_contract_ready"])
        self.assertFalse(result["release"]["v3_4_production_case_store_live_ready"])
        self.assertTrue(result["release"]["v3_5_runtime_control_plane_design_valid"])
        self.assertFalse(result["release"]["v3_5_runtime_authority_grant_allowed"])
        self.assertTrue(result["release"]["v3_6_advisory_runtime_pilot_valid"])
        self.assertFalse(result["release"]["v3_6_advisory_side_effects_executed"])
        self.assertTrue(result["release"]["v4_0_limited_runtime_authority_gate_complete"])
        self.assertFalse(result["release"]["v4_0_limited_runtime_authority_granted"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v4_1_to_v6_0_completes_readiness_gates_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        identity = evaluate_live_identity_evidence_gate(ROOT)
        approval = evaluate_live_approval_provider_gate(ROOT)
        case_store = evaluate_production_case_store_gate(ROOT)
        promotion = evaluate_release_promotion_execution_gate(ROOT)
        advisory = evaluate_governed_advisory_runtime(ROOT)
        controlled = evaluate_controlled_runtime_execution_gate(ROOT)
        hardening = evaluate_platform_hardening_assessment(ROOT)

        self.assertTrue(identity["live_identity_evidence_gate_complete"])
        self.assertFalse(identity["live_identity_authority_ready"])
        self.assertFalse(identity["mfa_claim_observed"])
        self.assertTrue(approval["live_approval_provider_gate_complete"])
        self.assertFalse(approval["live_approval_provider_ready"])
        self.assertFalse(approval["ai_approval_allowed"])
        self.assertTrue(case_store["production_case_store_gate_complete"])
        self.assertFalse(case_store["production_case_store_live_ready"])
        self.assertTrue(promotion["release_promotion_execution_gate_complete"])
        self.assertFalse(promotion["prod_deployment_executed"])
        self.assertTrue(advisory["governed_advisory_runtime_complete"])
        self.assertTrue(advisory["runtime_recommendation_only"])
        self.assertFalse(advisory["side_effects_executed"])
        self.assertFalse(advisory["production_mutation_executed"])
        self.assertTrue(controlled["controlled_runtime_execution_gate_complete"])
        self.assertFalse(controlled["controlled_runtime_execution_authorized"])
        self.assertIn("live_identity_authority_ready", controlled["blocked_reasons"])
        self.assertIn("live_approval_provider_ready", controlled["blocked_reasons"])
        self.assertIn("production_case_store_live_ready", controlled["blocked_reasons"])
        self.assertEqual(controlled["runtime_execution_readiness_percent"], 0.0)
        self.assertEqual(controlled["production_decision_authority_percent"], 0.0)
        self.assertTrue(hardening["hardening_assessment_complete"])
        self.assertFalse(hardening["platform_production_ready"])
        self.assertEqual(hardening["runtime_execution_readiness_percent"], 0.0)
        self.assertEqual(hardening["production_decision_authority_percent"], 0.0)
        self.assertTrue(result["release"]["v4_1_live_identity_evidence_gate_complete"])
        self.assertFalse(result["release"]["v4_1_live_identity_authority_ready"])
        self.assertTrue(result["release"]["v4_2_live_approval_provider_gate_complete"])
        self.assertFalse(result["release"]["v4_2_live_approval_provider_ready"])
        self.assertTrue(result["release"]["v4_3_production_case_store_gate_complete"])
        self.assertFalse(result["release"]["v4_3_production_case_store_live_ready"])
        self.assertTrue(result["release"]["v4_4_release_promotion_execution_gate_complete"])
        self.assertFalse(result["release"]["v4_4_prod_deployment_executed"])
        self.assertTrue(result["release"]["v5_0_governed_advisory_runtime_complete"])
        self.assertFalse(result["release"]["v5_0_side_effects_executed"])
        self.assertTrue(result["release"]["v5_5_controlled_runtime_execution_gate_complete"])
        self.assertFalse(result["release"]["v5_5_controlled_runtime_execution_authorized"])
        self.assertTrue(result["release"]["v6_0_platform_hardening_assessment_complete"])
        self.assertFalse(result["release"]["v6_0_platform_production_ready"])
        self.assertEqual(result["release"]["runtime_readiness_percent"], 0.0)
        self.assertEqual(result["release"]["production_decision_authority_percent"], 0.0)
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v6_1_to_v10_0_completes_plan_review_without_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        identity = evaluate_live_identity_authority(ROOT)
        approval = evaluate_live_decision_approval_provider(ROOT)
        case_store = evaluate_production_durable_case_store_readiness(ROOT)
        promotion = evaluate_production_promotion_chain_readiness(ROOT)
        runtime_pilot = evaluate_controlled_runtime_pilot_admission(ROOT)
        marketplace = evaluate_marketplace_runtime_governance(ROOT)
        shared_context = evaluate_shared_context_runtime_governance(ROOT)
        production_authority = evaluate_production_authority_readiness_review(ROOT)
        completion_plan = evaluate_completion_plan_execution(ROOT)

        self.assertTrue(identity["live_identity_authority_contract_complete"])
        self.assertFalse(identity["live_identity_authority_ready"])
        self.assertFalse(identity["mfa_claim_observed"])
        self.assertTrue(approval["live_decision_approval_provider_contract_complete"])
        self.assertFalse(approval["live_decision_approval_provider_ready"])
        self.assertFalse(approval["ai_approval_allowed"])
        self.assertTrue(case_store["production_durable_case_store_contract_complete"])
        self.assertFalse(case_store["production_durable_case_store_ready"])
        self.assertTrue(promotion["production_promotion_chain_contract_complete"])
        self.assertFalse(promotion["production_promotion_ready"])
        self.assertTrue(runtime_pilot["controlled_runtime_pilot_admission_complete"])
        self.assertFalse(runtime_pilot["controlled_runtime_pilot_authorized"])
        self.assertIn("live_identity_authority_ready", runtime_pilot["blocked_reasons"])
        self.assertIn("live_decision_approval_provider_ready", runtime_pilot["blocked_reasons"])
        self.assertIn("production_durable_case_store_ready", runtime_pilot["blocked_reasons"])
        self.assertTrue(marketplace["marketplace_runtime_governance_complete"])
        self.assertFalse(marketplace["marketplace_runtime_invocation_authorized"])
        self.assertFalse(marketplace["unrestricted_marketplace_execution_allowed"])
        self.assertTrue(shared_context["shared_context_runtime_governance_complete"])
        self.assertFalse(shared_context["runtime_context_exchange_authorized"])
        self.assertFalse(shared_context["direct_database_access_allowed"])
        self.assertTrue(production_authority["production_authority_readiness_review_complete"])
        self.assertFalse(production_authority["production_decision_authority_granted"])
        self.assertEqual(production_authority["runtime_execution_readiness_percent"], 0.0)
        self.assertEqual(production_authority["production_decision_authority_percent"], 0.0)
        self.assertTrue(completion_plan["autopilot_execution_review_complete"])
        self.assertEqual(completion_plan["reviewed_step_count"], 9)
        self.assertEqual(completion_plan["evidence_gate_complete_count"], 9)
        self.assertGreaterEqual(completion_plan["blocked_live_completion_count"], 8)
        self.assertTrue(completion_plan["product_vision_alignment_valid"])
        self.assertTrue(completion_plan["runtime_authority_grant_blocked"])
        self.assertTrue(completion_plan["production_decision_authority_blocked"])
        self.assertTrue(result["release"]["v6_1_live_identity_authority_contract_complete"])
        self.assertFalse(result["release"]["v6_1_live_identity_authority_ready"])
        self.assertFalse(result["release"]["v6_1_mfa_claim_observed"])
        self.assertTrue(result["release"]["v6_2_live_decision_approval_provider_contract_complete"])
        self.assertFalse(result["release"]["v6_2_live_decision_approval_provider_ready"])
        self.assertFalse(result["release"]["v6_2_ai_approval_allowed"])
        self.assertTrue(result["release"]["v6_3_production_durable_case_store_contract_complete"])
        self.assertFalse(result["release"]["v6_3_production_durable_case_store_ready"])
        self.assertTrue(result["release"]["v6_4_production_promotion_chain_contract_complete"])
        self.assertFalse(result["release"]["v6_4_production_promotion_ready"])
        self.assertTrue(result["release"]["v7_0_controlled_runtime_pilot_admission_complete"])
        self.assertFalse(result["release"]["v7_0_controlled_runtime_pilot_authorized"])
        self.assertTrue(result["release"]["v7_5_marketplace_runtime_governance_complete"])
        self.assertFalse(result["release"]["v7_5_marketplace_runtime_invocation_authorized"])
        self.assertFalse(result["release"]["v7_5_unrestricted_marketplace_execution_allowed"])
        self.assertTrue(result["release"]["v8_0_shared_context_runtime_governance_complete"])
        self.assertFalse(result["release"]["v8_0_runtime_context_exchange_authorized"])
        self.assertFalse(result["release"]["v8_0_direct_database_access_allowed"])
        self.assertTrue(result["release"]["v9_0_production_authority_readiness_review_complete"])
        self.assertFalse(result["release"]["v9_0_production_decision_authority_granted"])
        self.assertTrue(result["release"]["v10_0_completion_plan_execution_observed"])
        self.assertTrue(result["release"]["v10_0_autopilot_execution_review_complete"])
        self.assertEqual(result["release"]["v10_0_reviewed_step_count"], 9)
        self.assertEqual(result["release"]["v10_0_evidence_gate_complete_count"], 9)
        self.assertGreaterEqual(result["release"]["v10_0_blocked_live_completion_count"], 8)
        self.assertTrue(result["release"]["v10_0_product_vision_alignment_valid"])
        self.assertTrue(result["release"]["v10_0_runtime_authority_grant_blocked"])
        self.assertTrue(result["release"]["v10_0_production_decision_authority_blocked"])
        self.assertEqual(result["release"]["runtime_readiness_percent"], 0.0)
        self.assertEqual(result["release"]["production_decision_authority_percent"], 0.0)
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v2_0_assesses_runtime_readiness_without_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v10.0.0-pre")
        runtime = build_runtime_readiness_assessment(ROOT)
        surface = build_product_review_surface(ROOT)

        self.assertTrue(runtime["computed"])
        self.assertEqual(runtime["runtime_readiness_percent"], 0.0)
        self.assertEqual(runtime["production_decision_authority_percent"], 0.0)
        self.assertGreaterEqual(len(runtime["runtime_blockers"]), 10)
        self.assertFalse(runtime["runtime_integration_authorized"])
        self.assertFalse(runtime["production_decision_execution_authorized"])
        self.assertTrue(surface["computed"])
        self.assertGreaterEqual(surface["surface_count"], 8)
        self.assertFalse(surface["runtime_integration_authorized"])
        self.assertTrue(result["release"]["runtime_readiness_assessment_observed"])
        self.assertEqual(result["release"]["runtime_readiness_percent"], 0.0)
        self.assertTrue(result["release"]["product_review_surface_observed"])

    def test_v11_contract_foundation_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v11.0.0-pre")
        api = evaluate_api_architecture_contract(ROOT)
        product_packs = evaluate_product_pack_foundation(ROOT)
        certification = evaluate_shared_service_certification(ROOT)
        inventory = evaluate_ml_shared_capability_inventory(ROOT)
        adapter = evaluate_adapter_evidence_contract(ROOT)
        governance_store = evaluate_governance_store_contract(ROOT)
        runtime_authority = evaluate_runtime_authority_blocked_model(ROOT)
        v11 = evaluate_v11_platform_foundation(ROOT)

        self.assertTrue(api["api_architecture_contract_valid"])
        self.assertTrue(api["rest_authoritative"])
        self.assertTrue(api["websocket_notification_only"])
        self.assertTrue(api["event_recovery_rest_twin_declared"])
        self.assertTrue(api["topology_flexible"])
        self.assertFalse(api["forced_microservice_topology"])
        self.assertTrue(product_packs["product_pack_foundation_valid"])
        self.assertTrue(product_packs["edi_product_pack_observed"])
        self.assertTrue(product_packs["ml_product_pack_observed"])
        self.assertTrue(product_packs["support_product_pack_observed"])
        self.assertTrue(product_packs["all_product_packs_runtime_blocked"])
        self.assertTrue(certification["shared_service_certification_valid"])
        self.assertEqual(certification["certification_evidence_complete_count"], 0)
        self.assertTrue(inventory["ml_inventory_valid"])
        self.assertTrue(inventory["algo_engine_observe_first"])
        self.assertTrue(adapter["adapter_evidence_contract_valid"])
        self.assertFalse(adapter["result_without_evidence_allowed"])
        self.assertTrue(governance_store["governance_store_contract_valid"])
        self.assertFalse(governance_store["edi_is_universal_governance_store"])
        self.assertFalse(governance_store["direct_database_access_allowed"])
        self.assertTrue(runtime_authority["runtime_authority_blocked_model_valid"])
        self.assertEqual(runtime_authority["runtime_authority"], "blocked")
        self.assertFalse(runtime_authority["authority_granted"])
        self.assertTrue(v11["v11_platform_foundation_valid"])
        self.assertFalse(v11["forced_microservice_topology"])
        self.assertFalse(v11["websocket_authority_allowed"])
        self.assertFalse(v11["direct_database_access_allowed"])
        self.assertFalse(v11["edi_universal_governance_store"])
        self.assertTrue(result["release"]["v11_0_api_architecture_contract_valid"])
        self.assertTrue(result["release"]["v11_0_rest_authoritative"])
        self.assertTrue(result["release"]["v11_0_websocket_notification_only"])
        self.assertTrue(result["release"]["v11_0_topology_flexible"])
        self.assertFalse(result["release"]["v11_0_forced_microservice_topology"])
        self.assertTrue(result["release"]["v11_0_product_pack_foundation_valid"])
        self.assertTrue(result["release"]["v11_0_shared_service_certification_valid"])
        self.assertEqual(result["release"]["v11_0_service_certification_evidence_complete_count"], 0)
        self.assertTrue(result["release"]["v11_0_ml_shared_capability_inventory_valid"])
        self.assertTrue(result["release"]["v11_0_algo_engine_observe_first"])
        self.assertTrue(result["release"]["v11_0_adapter_evidence_contract_valid"])
        self.assertTrue(result["release"]["v11_0_governance_store_contract_valid"])
        self.assertFalse(result["release"]["v11_0_edi_universal_governance_store"])
        self.assertFalse(result["release"]["v11_0_direct_database_access_allowed"])
        self.assertTrue(result["release"]["v11_0_runtime_authority_blocked_model_valid"])
        self.assertTrue(result["release"]["v11_0_runtime_authority_blocked"])
        self.assertTrue(result["release"]["v11_0_platform_foundation_valid"])
        self.assertEqual(
            result["release"]["v11_0_foundation_gate_complete_count"],
            result["release"]["v11_0_foundation_gate_count"],
        )
        self.assertFalse(result["release"]["runtime_integration_authorized"])
        self.assertFalse(result["release"]["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v15_api_foundation_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v15.0.0-pre")
        certification_states = evaluate_shared_capability_certification_states(ROOT)
        product_contracts = evaluate_product_pack_contracts(ROOT)
        rest_api = evaluate_rest_api_contracts(ROOT)
        event_recovery = evaluate_event_recovery_contract(ROOT)
        foundation = evaluate_v15_api_foundation(ROOT)

        self.assertTrue(certification_states["shared_capability_certification_states_valid"])
        self.assertEqual(certification_states["certified_capability_count"], 0)
        self.assertEqual(certification_states["runtime_invocation_allowed_count"], 0)
        self.assertTrue(product_contracts["product_pack_contracts_valid"])
        self.assertFalse(product_contracts["cross_product_database_access_allowed"])
        self.assertEqual(product_contracts["runtime_authority_granted_count"], 0)
        self.assertTrue(rest_api["rest_api_contracts_valid"])
        self.assertTrue(rest_api["rest_authoritative"])
        self.assertTrue(rest_api["runtime_authority_default_blocked"])
        self.assertTrue(event_recovery["event_recovery_contract_valid"])
        self.assertFalse(event_recovery["websocket_authoritative"])
        self.assertFalse(event_recovery["events_mutate_business_state"])
        self.assertTrue(event_recovery["rest_recovery_required"])
        self.assertTrue(foundation["v15_api_foundation_valid"])
        self.assertEqual(
            foundation["foundation_gate_complete_count"],
            foundation["foundation_gate_count"],
        )
        self.assertTrue(result["release"]["v12_0_shared_capability_certification_states_valid"])
        self.assertEqual(result["release"]["v12_0_certified_capability_count"], 0)
        self.assertEqual(result["release"]["v12_0_runtime_invocation_allowed_count"], 0)
        self.assertTrue(result["release"]["v13_0_product_pack_contracts_valid"])
        self.assertFalse(result["release"]["v13_0_cross_product_database_access_allowed"])
        self.assertEqual(result["release"]["v13_0_runtime_authority_granted_count"], 0)
        self.assertTrue(result["release"]["v14_0_rest_api_contracts_valid"])
        self.assertTrue(result["release"]["v14_0_rest_authoritative"])
        self.assertTrue(result["release"]["v14_0_runtime_authority_default_blocked"])
        self.assertTrue(result["release"]["v15_0_event_recovery_contract_valid"])
        self.assertFalse(result["release"]["v15_0_websocket_authoritative"])
        self.assertFalse(result["release"]["v15_0_events_mutate_business_state"])
        self.assertTrue(result["release"]["v15_0_rest_recovery_required"])
        self.assertTrue(result["release"]["v15_0_api_foundation_valid"])
        self.assertFalse(result["release"]["runtime_integration_authorized"])
        self.assertFalse(result["release"]["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v20_architecture_closure_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v20.0.0-pre")
        certification = evaluate_certification_evidence_packs(ROOT)
        admission = evaluate_product_pack_admission(ROOT)
        openapi = evaluate_openapi_skeleton(ROOT)
        events = evaluate_event_recovery_fixtures(ROOT)
        governance_schema = evaluate_governance_store_logical_schema(ROOT)
        closure = evaluate_v20_architecture_closure(ROOT)

        self.assertTrue(certification["certification_evidence_packs_valid"])
        self.assertEqual(certification["certified_service_count"], 0)
        self.assertEqual(certification["runtime_invocation_allowed_count"], 0)
        self.assertTrue(admission["product_pack_admission_valid"])
        self.assertFalse(admission["direct_database_access_allowed"])
        self.assertFalse(admission["hidden_shared_state_allowed"])
        self.assertEqual(admission["runtime_authority_granted_count"], 0)
        self.assertTrue(openapi["openapi_skeleton_valid"])
        self.assertTrue(openapi["rest_authoritative"])
        self.assertTrue(openapi["runtime_authority_blocked_response"])
        self.assertTrue(events["event_recovery_fixtures_valid"])
        self.assertFalse(events["websocket_authoritative"])
        self.assertFalse(events["events_mutate_business_state"])
        self.assertTrue(events["all_events_recoverable"])
        self.assertTrue(governance_schema["governance_store_logical_schema_valid"])
        self.assertFalse(governance_schema["storage_backend_selected"])
        self.assertFalse(governance_schema["direct_database_access_allowed"])
        self.assertTrue(governance_schema["append_only_required"])
        self.assertTrue(closure["v20_architecture_closure_valid"])
        self.assertEqual(closure["closure_gate_complete_count"], closure["closure_gate_count"])
        self.assertTrue(result["release"]["v16_0_certification_evidence_packs_valid"])
        self.assertEqual(result["release"]["v16_0_certified_service_count"], 0)
        self.assertEqual(result["release"]["v16_0_runtime_invocation_allowed_count"], 0)
        self.assertTrue(result["release"]["v17_0_product_pack_admission_valid"])
        self.assertFalse(result["release"]["v17_0_direct_database_access_allowed"])
        self.assertFalse(result["release"]["v17_0_hidden_shared_state_allowed"])
        self.assertEqual(result["release"]["v17_0_runtime_authority_granted_count"], 0)
        self.assertTrue(result["release"]["v18_0_openapi_skeleton_valid"])
        self.assertTrue(result["release"]["v18_0_runtime_authority_blocked_response"])
        self.assertTrue(result["release"]["v19_0_event_recovery_fixtures_valid"])
        self.assertFalse(result["release"]["v19_0_websocket_authoritative"])
        self.assertFalse(result["release"]["v19_0_events_mutate_business_state"])
        self.assertTrue(result["release"]["v19_0_all_events_recoverable"])
        self.assertTrue(result["release"]["v20_0_governance_store_logical_schema_valid"])
        self.assertFalse(result["release"]["v20_0_storage_backend_selected"])
        self.assertFalse(result["release"]["v20_0_direct_database_access_allowed"])
        self.assertTrue(result["release"]["v20_0_append_only_required"])
        self.assertTrue(result["release"]["v20_0_architecture_closure_valid"])
        self.assertFalse(result["release"]["runtime_integration_authorized"])
        self.assertFalse(result["release"]["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v25_contract_closure_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v25.0.0-pre")
        openapi = evaluate_canonical_openapi_contract(ROOT)
        product_kit = evaluate_product_pack_contract_kit(ROOT)
        adapter_kit = evaluate_adapter_evidence_contract_kit(ROOT)
        governance_api = evaluate_governance_store_logical_api(ROOT)
        events = evaluate_event_recovery_contract_v2(ROOT)
        closure = evaluate_v25_contract_closure(ROOT)

        self.assertTrue(openapi["canonical_openapi_contract_valid"])
        self.assertTrue(openapi["rest_authoritative"])
        self.assertTrue(openapi["all_commands_require_idempotency"])
        self.assertTrue(openapi["all_commands_require_correlation"])
        self.assertTrue(openapi["runtime_authority_blocked_response"])
        self.assertFalse(openapi["websocket_authoritative"])
        self.assertTrue(product_kit["product_pack_contract_kit_valid"])
        self.assertFalse(product_kit["direct_database_access_allowed"])
        self.assertFalse(product_kit["hidden_shared_state_allowed"])
        self.assertEqual(product_kit["runtime_authority_granted_count"], 0)
        self.assertTrue(adapter_kit["adapter_evidence_contract_kit_valid"])
        self.assertEqual(adapter_kit["live_invocation_allowed_count"], 0)
        self.assertTrue(adapter_kit["sample_evidence_present"])
        self.assertTrue(governance_api["governance_store_logical_api_valid"])
        self.assertFalse(governance_api["storage_backend_selected"])
        self.assertFalse(governance_api["direct_database_access_allowed"])
        self.assertFalse(governance_api["delete_operation_allowed"])
        self.assertTrue(governance_api["projection_rebuild_required"])
        self.assertTrue(events["event_recovery_contract_v2_valid"])
        self.assertFalse(events["websocket_authoritative"])
        self.assertFalse(events["events_mutate_business_state"])
        self.assertTrue(events["rest_event_log_required"])
        self.assertTrue(events["reconnect_recovery_required"])
        self.assertTrue(closure["v25_contract_closure_valid"])
        self.assertEqual(closure["closure_gate_complete_count"], closure["closure_gate_count"])
        self.assertTrue(result["release"]["v21_0_canonical_openapi_contract_valid"])
        self.assertTrue(result["release"]["v21_0_all_commands_require_idempotency"])
        self.assertTrue(result["release"]["v21_0_all_commands_require_correlation"])
        self.assertFalse(result["release"]["v21_0_websocket_authoritative"])
        self.assertTrue(result["release"]["v22_0_product_pack_contract_kit_valid"])
        self.assertFalse(result["release"]["v22_0_direct_database_access_allowed"])
        self.assertFalse(result["release"]["v22_0_hidden_shared_state_allowed"])
        self.assertEqual(result["release"]["v22_0_runtime_authority_granted_count"], 0)
        self.assertTrue(result["release"]["v23_0_adapter_evidence_contract_kit_valid"])
        self.assertEqual(result["release"]["v23_0_live_invocation_allowed_count"], 0)
        self.assertTrue(result["release"]["v24_0_governance_store_logical_api_valid"])
        self.assertFalse(result["release"]["v24_0_storage_backend_selected"])
        self.assertFalse(result["release"]["v24_0_direct_database_access_allowed"])
        self.assertFalse(result["release"]["v24_0_delete_operation_allowed"])
        self.assertTrue(result["release"]["v25_0_event_recovery_contract_v2_valid"])
        self.assertFalse(result["release"]["v25_0_websocket_authoritative"])
        self.assertFalse(result["release"]["v25_0_events_mutate_business_state"])
        self.assertTrue(result["release"]["v25_0_contract_closure_valid"])
        self.assertFalse(result["release"]["runtime_integration_authorized"])
        self.assertFalse(result["release"]["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v30_platform_operating_model_closure_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v30.0.0-pre")
        certification = evaluate_shared_capability_certification_workflow(ROOT)
        runtime_gate = evaluate_runtime_authority_gate_contract(ROOT)
        cost_usage = evaluate_cost_usage_evidence_contract(ROOT)
        semantic_projection = evaluate_shared_context_semantic_projection_contract(ROOT)
        developer_kit = evaluate_product_pack_developer_kit(ROOT)
        closure = evaluate_v30_platform_operating_model_closure(ROOT)

        self.assertTrue(certification["certification_workflow_valid"])
        self.assertEqual(certification["certified_count"], 0)
        self.assertEqual(certification["runtime_invocation_allowed_count"], 0)
        self.assertTrue(runtime_gate["runtime_authority_gate_contract_valid"])
        self.assertFalse(runtime_gate["runtime_authority_granted"])
        self.assertTrue(runtime_gate["negative_fixtures_block_authority"])
        self.assertTrue(cost_usage["cost_usage_evidence_contract_valid"])
        self.assertFalse(cost_usage["billing_integration_enabled"])
        self.assertEqual(cost_usage["live_invocation_observed_count"], 0)
        self.assertTrue(semantic_projection["semantic_projection_contract_valid"])
        self.assertFalse(semantic_projection["direct_database_access_allowed"])
        self.assertFalse(semantic_projection["hidden_shared_state_allowed"])
        self.assertFalse(semantic_projection["runtime_context_exchange_authorized"])
        self.assertTrue(developer_kit["developer_kit_valid"])
        self.assertEqual(developer_kit["runtime_authority_granted_count"], 0)
        self.assertFalse(developer_kit["direct_database_access_allowed"])
        self.assertTrue(closure["v30_platform_operating_model_closure_valid"])
        self.assertEqual(closure["closure_gate_complete_count"], closure["closure_gate_count"])
        self.assertTrue(result["release"]["v26_0_certification_workflow_valid"])
        self.assertEqual(result["release"]["v26_0_certified_count"], 0)
        self.assertEqual(result["release"]["v26_0_runtime_invocation_allowed_count"], 0)
        self.assertTrue(result["release"]["v27_0_runtime_authority_gate_contract_valid"])
        self.assertFalse(result["release"]["v27_0_runtime_authority_granted"])
        self.assertTrue(result["release"]["v27_0_negative_fixtures_block_authority"])
        self.assertTrue(result["release"]["v28_0_cost_usage_evidence_contract_valid"])
        self.assertFalse(result["release"]["v28_0_billing_integration_enabled"])
        self.assertEqual(result["release"]["v28_0_live_invocation_observed_count"], 0)
        self.assertTrue(result["release"]["v29_0_semantic_projection_contract_valid"])
        self.assertFalse(result["release"]["v29_0_direct_database_access_allowed"])
        self.assertFalse(result["release"]["v29_0_runtime_context_exchange_authorized"])
        self.assertTrue(result["release"]["v30_0_product_pack_developer_kit_valid"])
        self.assertEqual(result["release"]["v30_0_runtime_authority_granted_count"], 0)
        self.assertFalse(result["release"]["v30_0_direct_database_access_allowed"])
        self.assertTrue(result["release"]["v30_0_platform_operating_model_closure_valid"])

    def test_v35_usability_governance_closure_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v35.0.0-pre")

        compatibility = evaluate_contract_compatibility_versioning(ROOT)
        policy_tests = evaluate_policy_test_pack_framework(ROOT)
        cli_scaffold = evaluate_product_pack_cli_scaffold_contract(ROOT)
        query_contract = evaluate_case_evidence_query_contract(ROOT)
        dashboard = evaluate_governance_dashboard_data_contract(ROOT)
        closure = evaluate_v35_usability_governance_closure(ROOT)

        self.assertTrue(compatibility["compatibility_versioning_valid"])
        self.assertTrue(compatibility["breaking_change_requires_major"])
        self.assertTrue(policy_tests["policy_test_pack_framework_valid"])
        self.assertTrue(policy_tests["deterministic_policy_first"])
        self.assertFalse(policy_tests["ai_policy_override_allowed"])
        self.assertTrue(cli_scaffold["product_pack_cli_scaffold_valid"])
        self.assertFalse(cli_scaffold["no_code_builder"])
        self.assertEqual(cli_scaffold["runtime_authority_default"], "none")
        self.assertFalse(cli_scaffold["direct_database_access_allowed"])
        self.assertEqual(cli_scaffold["runtime_authority_creating_command_count"], 0)
        self.assertTrue(query_contract["case_evidence_query_contract_valid"])
        self.assertTrue(query_contract["rest_authoritative"])
        self.assertFalse(query_contract["production_backend_selected"])
        self.assertTrue(dashboard["governance_dashboard_data_contract_valid"])
        self.assertTrue(dashboard["derived_from_rest_evidence"])
        self.assertFalse(dashboard["dashboard_is_source_of_truth"])
        self.assertFalse(dashboard["websocket_authoritative"])
        self.assertTrue(closure["v35_usability_governance_closure_valid"])
        self.assertFalse(closure["runtime_integration_authorized"])
        self.assertFalse(closure["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["v31_0_compatibility_versioning_valid"])
        self.assertTrue(result["release"]["v32_0_policy_test_pack_framework_valid"])
        self.assertFalse(result["release"]["v32_0_ai_policy_override_allowed"])
        self.assertTrue(result["release"]["v33_0_product_pack_cli_scaffold_valid"])
        self.assertFalse(result["release"]["v33_0_no_code_builder"])
        self.assertEqual(result["release"]["v33_0_runtime_authority_creating_command_count"], 0)
        self.assertTrue(result["release"]["v34_0_case_evidence_query_contract_valid"])
        self.assertFalse(result["release"]["v34_0_production_backend_selected"])
        self.assertTrue(result["release"]["v35_0_governance_dashboard_data_contract_valid"])
        self.assertFalse(result["release"]["v35_0_dashboard_is_source_of_truth"])
        self.assertFalse(result["release"]["v35_0_websocket_authoritative"])
        self.assertTrue(result["release"]["v35_0_usability_governance_closure_valid"])
        self.assertFalse(result["release"]["runtime_integration_authorized"])
        self.assertFalse(result["release"]["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v40_usability_acceptance_pack_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v40.0.0-pre")

        authoring = evaluate_product_pack_authoring_ux_contract(ROOT)
        queue = evaluate_governance_review_queue_contract(ROOT)
        lineage = evaluate_capability_lineage_explorer_contract(ROOT)
        replay_workspace = evaluate_replay_workspace_contract(ROOT)
        acceptance = evaluate_v40_usability_acceptance_pack(ROOT)

        self.assertTrue(authoring["product_pack_authoring_ux_valid"])
        self.assertTrue(authoring["rest_authoritative"])
        self.assertFalse(authoring["websocket_authoritative"])
        self.assertFalse(authoring["broad_no_code_builder"])
        self.assertFalse(authoring["direct_database_access_allowed"])
        self.assertTrue(queue["governance_review_queue_valid"])
        self.assertTrue(queue["solo_maintainer_exception_visible"])
        self.assertFalse(queue["approval_automation_allowed"])
        self.assertTrue(lineage["capability_lineage_explorer_valid"])
        self.assertTrue(lineage["capability_version_lineage_required"])
        self.assertFalse(lineage["direct_runtime_invocation_allowed"])
        self.assertTrue(replay_workspace["replay_workspace_valid"])
        self.assertTrue(replay_workspace["drift_comparison_required"])
        self.assertFalse(replay_workspace["runtime_execution_allowed"])
        self.assertFalse(replay_workspace["side_effects_allowed"])
        self.assertTrue(acceptance["v40_usability_acceptance_pack_valid"])
        self.assertTrue(acceptance["runtime_remains_blocked"])
        self.assertFalse(acceptance["websocket_authoritative"])
        self.assertFalse(acceptance["runtime_integration_authorized"])
        self.assertFalse(acceptance["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["v36_0_product_pack_authoring_ux_valid"])
        self.assertFalse(result["release"]["v36_0_websocket_authoritative"])
        self.assertFalse(result["release"]["v36_0_broad_no_code_builder"])
        self.assertTrue(result["release"]["v37_0_governance_review_queue_valid"])
        self.assertFalse(result["release"]["v37_0_approval_automation_allowed"])
        self.assertTrue(result["release"]["v38_0_capability_lineage_explorer_valid"])
        self.assertFalse(result["release"]["v38_0_direct_runtime_invocation_allowed"])
        self.assertTrue(result["release"]["v39_0_replay_workspace_valid"])
        self.assertFalse(result["release"]["v39_0_runtime_execution_allowed"])
        self.assertFalse(result["release"]["v39_0_side_effects_allowed"])
        self.assertTrue(result["release"]["v40_0_usability_acceptance_pack_valid"])
        self.assertTrue(result["release"]["v40_0_runtime_remains_blocked"])
        self.assertFalse(result["release"]["v40_0_websocket_authoritative"])
        self.assertFalse(result["release"]["runtime_integration_authorized"])
        self.assertFalse(result["release"]["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v45_platform_operator_readiness_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v45.0.0-pre")

        retention = evaluate_evidence_retention_legal_hold_contract(ROOT)
        boundary = evaluate_tenant_workspace_boundary_contract(ROOT)
        entitlement = evaluate_entitlement_usage_gate_contract(ROOT)
        certification = evaluate_integration_certification_ux_contract(ROOT)
        readiness = evaluate_platform_operator_readiness_pack(ROOT)

        self.assertTrue(retention["evidence_retention_legal_hold_valid"])
        self.assertFalse(retention["production_backend_selected"])
        self.assertTrue(boundary["tenant_workspace_boundary_valid"])
        self.assertFalse(boundary["cross_tenant_access_allowed"])
        self.assertFalse(boundary["direct_database_access_allowed"])
        self.assertFalse(boundary["live_multi_tenant_enforcement_observed"])
        self.assertTrue(entitlement["entitlement_usage_gate_valid"])
        self.assertFalse(entitlement["billing_integration_enabled"])
        self.assertFalse(entitlement["runtime_enforcement_claimed"])
        self.assertTrue(certification["integration_certification_ux_valid"])
        self.assertEqual(certification["certified_count"], 0)
        self.assertEqual(certification["runtime_invocation_allowed_count"], 0)
        self.assertFalse(certification["ui_is_source_of_truth"])
        self.assertTrue(readiness["platform_operator_readiness_pack_valid"])
        self.assertTrue(readiness["unsafe_claims_visible"])
        self.assertTrue(readiness["runtime_remains_blocked"])
        self.assertFalse(readiness["runtime_integration_authorized"])
        self.assertFalse(readiness["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["v41_0_evidence_retention_legal_hold_valid"])
        self.assertFalse(result["release"]["v41_0_production_backend_selected"])
        self.assertTrue(result["release"]["v42_0_tenant_workspace_boundary_valid"])
        self.assertFalse(result["release"]["v42_0_live_multi_tenant_enforcement_observed"])
        self.assertTrue(result["release"]["v43_0_entitlement_usage_gate_valid"])
        self.assertFalse(result["release"]["v43_0_billing_integration_enabled"])
        self.assertFalse(result["release"]["v43_0_runtime_enforcement_claimed"])
        self.assertTrue(result["release"]["v44_0_integration_certification_ux_valid"])
        self.assertEqual(result["release"]["v44_0_certified_count"], 0)
        self.assertEqual(result["release"]["v44_0_runtime_invocation_allowed_count"], 0)
        self.assertTrue(result["release"]["v45_0_platform_operator_readiness_pack_valid"])
        self.assertTrue(result["release"]["v45_0_runtime_remains_blocked"])
        self.assertFalse(result["release"]["runtime_integration_authorized"])
        self.assertFalse(result["release"]["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["release_acceptance_passed"])

    def test_v50_platform_governance_closure_without_runtime_authority(self) -> None:
        result = write_v0_2_evidence(ROOT, ROOT / "reports" / "trust-loop", "v50.0.0-pre")

        repository = evaluate_repository_governance_evidence_pack(ROOT)
        pr_policy = evaluate_pr_validation_policy(ROOT)
        exceptions = evaluate_governance_exception_register(ROOT)
        edi = evaluate_edi_observer_ingestion_contract(ROOT)
        closure = evaluate_platform_governance_closure_pack(ROOT)

        self.assertTrue(repository["repository_governance_evidence_pack_valid"])
        self.assertTrue(repository["security_policy_active"])
        self.assertTrue(repository["dependabot_enabled"])
        self.assertTrue(repository["actions_allowlist_observed"])
        self.assertTrue(pr_policy["pr_validation_policy_valid"])
        self.assertFalse(pr_policy["pr_requires_release_artifact"])
        self.assertTrue(pr_policy["release_requires_release_artifact"])
        self.assertFalse(pr_policy["release_acceptance_required_for_pr"])
        self.assertTrue(exceptions["governance_exception_register_valid"])
        self.assertGreaterEqual(exceptions["exception_count"], 2)
        self.assertEqual(exceptions["runtime_authority_granted_count"], 0)
        self.assertTrue(edi["edi_observer_ingestion_contract_valid"])
        self.assertFalse(edi["edi_is_authority"])
        self.assertTrue(closure["platform_governance_closure_pack_valid"])
        self.assertTrue(closure["runtime_remains_blocked"])
        self.assertFalse(closure["runtime_integration_authorized"])
        self.assertFalse(closure["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["v46_0_repository_governance_evidence_pack_valid"])
        self.assertTrue(result["release"]["v46_0_security_policy_active"])
        self.assertTrue(result["release"]["v46_0_dependabot_enabled"])
        self.assertTrue(result["release"]["v47_0_pr_validation_policy_valid"])
        self.assertFalse(result["release"]["v47_0_pr_requires_release_artifact"])
        self.assertTrue(result["release"]["v47_0_release_requires_release_artifact"])
        self.assertFalse(result["release"]["v47_0_release_acceptance_required_for_pr"])
        self.assertTrue(result["release"]["v48_0_governance_exception_register_valid"])
        self.assertEqual(result["release"]["v48_0_runtime_authority_granted_count"], 0)
        self.assertTrue(result["release"]["v49_0_edi_observer_ingestion_contract_valid"])
        self.assertFalse(result["release"]["v49_0_edi_is_authority"])
        self.assertTrue(result["release"]["v50_0_platform_governance_closure_pack_valid"])
        self.assertTrue(result["release"]["v50_0_runtime_remains_blocked"])
        self.assertFalse(result["release"]["runtime_integration_authorized"])
        self.assertFalse(result["release"]["production_decision_execution_authorized"])
        self.assertTrue(result["release"]["release_acceptance_passed"])


if __name__ == "__main__":
    unittest.main()
